artox_lab_health_check_ping_pong:
  path: /ping
  controller: ArtoxLab\Bundle\ClarcBundle\Core\Interfaces\UI\API\Controllers\PingPongController::ping
  methods: GET

artox_lab_user_permissions:
  path: /user/permissions
  controller: ArtoxLab\Bundle\ClarcBundle\Core\Interfaces\UI\API\Controllers\PermissionController::permissions
  methods: GET

artox_lab_user_navigations:
  path: /user/navigations
  controller: ArtoxLab\Bundle\ClarcBundle\Core\Interfaces\UI\API\Controllers\NavigationController::userNavigation
  methods: GET
