services:
  _defaults:
    autowire: true
    autoconfigure: true

  artox_lab_clarc.bus.command_bus:
    class: ArtoxLab\Bundle\ClarcBundle\Core\Interfaces\Bus\CommandBus\CommandBus

  artox_lab_clarc.bus.query_bus:
    class: ArtoxLab\Bundle\ClarcBundle\Core\Interfaces\Bus\QueryBus\QueryBus

  artox_lab_clarc.bus.event_bus:
    class: ArtoxLab\Bundle\ClarcBundle\Core\Interfaces\Bus\EventBus\EventBus

  artox_lab_clarc.bus.message_bus:
    class: ArtoxLab\Bundle\ClarcBundle\Core\Interfaces\Bus\MessageBus\MessageBus

  ArtoxLab\Bundle\ClarcBundle\Core\Interfaces\Bus\CommandBus\CommandBusInterface: '@artox_lab_clarc.bus.command_bus'

  ArtoxLab\Bundle\ClarcBundle\Core\Interfaces\Bus\QueryBus\QueryBusInterface: '@artox_lab_clarc.bus.query_bus'

  ArtoxLab\Bundle\ClarcBundle\Core\Entity\Bus\DomainEventBusInterface: '@artox_lab_clarc.bus.event_bus'

  ArtoxLab\Bundle\ClarcBundle\Core\Interfaces\Bus\MessageBus\MessageBusInterface: '@artox_lab_clarc.bus.message_bus'

  artox_lab_clarc.bus.validation:
    class: ArtoxLab\Bundle\ClarcBundle\Core\Interfaces\Bus\Middleware\ValidationMiddleware

  api_exception_subscriber:
    class: ArtoxLab\Bundle\ClarcBundle\Core\Interfaces\UI\API\EventListeners\ExceptionSubscriber
    arguments:
      $environment: '%kernel.environment%'
    tags:
      - { name: kernel.event_subscriber }

  ArtoxLab\Bundle\ClarcBundle\Command\Maker\:
    resource: '../../Command/Maker/*'
    exclude: '../../Command/Maker/{AbstractMaker.php}'
    tags: [ 'maker.command' ]

  ArtoxLab\Bundle\ClarcBundle\Core\Interfaces\UI\API\Requests\RequestResolver:
    tags:
      - { name: controller.argument_value_resolver, priority: 50 }

  League\Fractal\Serializer\Serializer:
    class: ArtoxLab\Bundle\ClarcBundle\Core\Interfaces\UI\API\Transformers\Serializers\NullObjectArraySerializer

  ArtoxLab\Bundle\ClarcBundle\Core\Interfaces\UI\API\Controllers\:
    resource: '../../Core/Interfaces/UI/API/Controllers/'
    tags: [ 'controller.service_arguments' ]
    calls: [ [ 'setContainer', [ '@service_container' ] ] ]

  # Use Cases
  ArtoxLab\Bundle\ClarcBundle\Core\UseCases\Queries\User\FindAllPermissions\Interactor: ~

  # Security
  artox_lab_clarc.security.authorization_checker:
    class: ArtoxLab\Bundle\ClarcBundle\Core\Interfaces\Security\AuthorizationChecker

  ### RBAC
  artox_lab_clarc.security.permission_storage:
    class: ArtoxLab\Bundle\ClarcBundle\Core\Interfaces\Security\PermissionStorage

  ArtoxLab\Bundle\ClarcBundle\Core\Entity\Security\PermissionLoader: '@artox_lab_clarc.security.rbac.config_permission_loader'
  ArtoxLab\Bundle\ClarcBundle\Core\Entity\Security\PermissionStorage: '@artox_lab_clarc.security.permission_storage'

  artox_lab_clarc.security.rbac.config_permission_loader:
    class: ArtoxLab\Bundle\ClarcBundle\Core\Interfaces\Security\ConfigPermissionLoader
    arguments:
      - 'rolesPermissions'

  ArtoxLab\Bundle\ClarcBundle\Core\Entity\Security\AuthorizationChecker: '@artox_lab_clarc.security.authorization_checker'
  ### RBAC Voters
  artox_lab_clarc.security.voter.role_permission:
    class: ArtoxLab\Bundle\ClarcBundle\Core\Interfaces\Security\Voters\RolePermissionVoter
    tags: ['security.voter']


