services:
  artox_lab_clarc.api.serializer:
    class: '%artox_lab_clarc.api.serializer.class%'

  artox_lab_clarc.command_bus:
    class: \ArtoxLab\Bundle\ClarcBundle\Core\Interfaces\CommandBus\CommandBus
    arguments: ['@command.bus']

  ArtoxLab\Bundle\ClarcBundle\Core\Interfaces\CommandBus\CommandBusInterface: '@artox_lab_clarc.command_bus'

  ArtoxLab\Bundle\ClarcBundle\Command\Maker\:
    resource: '../../Command/Maker/*'
    exclude: '../../Command/Maker/{AbstractMaker.php}'
    tags: ['maker.command']

  ArtoxLab\Bundle\ClarcBundle\Core\Interfaces\UI\API\Requests\RequestResolver:
    arguments:
      - '@validator'
    tags:
      - { name: controller.request_value_resolver, priority: 50 }
